<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6HdPdjF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6HdPdjF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container6HdPdjF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container6HdPdjF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container6HdPdjF\appAppKernelProdContainer([
    'container.build_hash' => '6HdPdjF',
    'container.build_id' => 'bf873ab3',
    'container.build_time' => 1710148010,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6HdPdjF');
