### docker-compose.yml
version: "3"
   
services:
  web:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./nginx/certificados:/certificados
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      
  php:
    build: php
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      
  bd:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - datos:/var/lib/mysql
      - ./bd/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./bd:/bd

volumes:
  datos:
