### docker-compose.yml
version: "3"
   
services:
  web:
    image: nginx:latest
    env_file:
      - .env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./nginx/certificados:/certificados
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      
  php:
    build: php
    env_file:
      - .env.prod
    volumes:
      - ./app:/app
      - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf